# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PycharmProjects\OCR\OCR_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QDesktopServices
from my_telnetlib_ck import *
from funcs import *
from time import sleep
from functools import wraps
import sys
from my_logger import *
from ipaddress import IPv4Address
from dataClass import *
import traceback
from threading import Thread
#

def dutConnet(dutInfo,maxRetryTimes=20,retryInterval=10):
    tel = TelnetClient()
    for i in range(maxRetryTimes):
        if tel.login_host(dutInfo["ip"],dutInfo["UserName"],dutInfo["PassWord"],dutInfo['port']):
            return tel #连接成功则返回TelnetClient对象
        else:
            sleep(retryInterval) #连接失败重连间隔时间
    return False #返回失败值


class Worker(QThread):
    logSignal = pyqtSignal(int)
    
    def __init__(self,textEdit,logFn,maxNum):
        super(Worker,self).__init__()
        self.version = '2.34'
        self.stopped = False
        self.t = textEdit
        self.f = logFn
        self.n = int(maxNum)

    def run(self):
        # sleep(3)
        try:
            while not self.stopped:
                # 检查行数
                line_count = self.t.document().blockCount()
                if line_count > self.n:
                    # 发送信号以清空文本
                    txt = self.t.toPlainText()
                    self.logSignal.emit(0)
                    writeCfgTxt(txt,self.f,mode='a+')
                # 等待一段时间再继续检查
                self.msleep(1000)
        except Exception as e:
            print(e)

    def stop(self):
        self.stopped = True


class MainThread(QThread):
    signal = pyqtSignal()

    def __init__(self, target=None):
        super().__init__()
        self.target = target
        
    def run(self):
        if self.target:
            self.target()
        self.is_running = True
            
    def stop(self):
        self.is_running = False
        self.terminate()

class getAreaThread(QThread):
    finished_signal = pyqtSignal()
    result_signal = pyqtSignal(str)  # 新增结果信号
    error_signal = pyqtSignal(str)  # 新增错误信号
    def __init__(self, parent=None):
        super().__init__(parent)
        self.result = None  # 存储结果

    def run(self):
        # 执行耗时操作
        try:
            result = getAreaTupleFunc()
            self.result = result  # 存储结果
            self.result_signal.emit(result)  # 发送结果信号
        except Exception as e:
            self.error_signal.emit(f"坐标获取失败: {str(e)}")
        finally:
            self.finished_signal.emit() # 发送完成信号


class EmittingStr(QtCore.QObject):
    textWritten = QtCore.pyqtSignal(str) #定义一个发送str的信号
    def write(self, text):
      self.textWritten.emit(str(text))

class Ui_OCR_UI(object):    
    def __init__(self):
        # 将输出重定向到logText中
        sys.stdout = EmittingStr(textWritten=self.outputWritten)
        sys.stderr = EmittingStr(textWritten=self.outputWritten)

    #异常捕捉器
    def error_handler(func):
        @wraps(func) #关键行, 旨在消除装饰器对原函数造成的影响，即对原函数的相关属性进行拷贝，已达到装饰器不修改原函数的目的。
        def wrapper(self):
            try:
                return func(self)
            except:
                msg=traceback.format_exc()
                print(msg)
                return 'error'
        return wrapper #返回函数名
    
    def error_ignore(func):
        @wraps(func) #关键行, 旨在消除装饰器对原函数造成的影响，即对原函数的相关属性进行拷贝，已达到装饰器不修改原函数的目的。
        def wrapper(self):
            try:
                return func(self)
            except:
                return 'error'
        return wrapper #返回函数名

    def setupUi(self, OCR_UI):
        OCR_UI.setObjectName("OCR_UI")
        OCR_UI.setEnabled(True)
        OCR_UI.resize(1111, 763)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OCR_UI.sizePolicy().hasHeightForWidth())
        OCR_UI.setSizePolicy(sizePolicy)
        OCR_UI.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(OCR_UI)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.verticalLayout_Left = QtWidgets.QVBoxLayout()
        self.verticalLayout_Left.setObjectName("verticalLayout_Left")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.DutInfoLayout_6 = QtWidgets.QGridLayout()
        self.DutInfoLayout_6.setObjectName("DutInfoLayout_6")
        self.StatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.StatusLabel.setObjectName("StatusLabel")
        self.DutInfoLayout_6.addWidget(self.StatusLabel, 6, 1, 1, 2)
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.DutInfoLayout_6.addWidget(self.line_16, 5, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.DutInfoLayout_6.addWidget(self.label, 1, 0, 1, 3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 3)
        self.logText = QtWidgets.QTextEdit(self.centralwidget)
        self.logText.setEnabled(True)
        self.logText.setFrameShape(QtWidgets.QFrame.Box)
        self.logText.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logText.setLineWidth(0)
        self.logText.setMidLineWidth(1)
        self.logText.setReadOnly(True)
        self.logText.setObjectName("logText")
        self.gridLayout.addWidget(self.logText, 5, 0, 1, 3)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 2, 0, 1, 3)
        self.DutInfoLayout_6.addLayout(self.gridLayout, 8, 0, 1, 4)
        self.dutUn = QtWidgets.QLineEdit(self.centralwidget)
        self.dutUn.setObjectName("dutUn")
        self.DutInfoLayout_6.addWidget(self.dutUn, 3, 1, 1, 1)
        self.dutIP = QtWidgets.QLineEdit(self.centralwidget)
        self.dutIP.setObjectName("dutIP")
        self.DutInfoLayout_6.addWidget(self.dutIP, 2, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.DutInfoLayout_6.addWidget(self.line_5, 0, 0, 1, 4)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setObjectName("label_15")
        self.DutInfoLayout_6.addWidget(self.label_15, 6, 0, 1, 1)
        self.beginButton = QtWidgets.QPushButton(self.centralwidget)
        self.beginButton.setObjectName("beginButton")
        self.DutInfoLayout_6.addWidget(self.beginButton, 2, 2, 1, 1)
        self.dutIPLabel = QtWidgets.QLabel(self.centralwidget)
        self.dutIPLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dutIPLabel.setObjectName("dutIPLabel")
        self.DutInfoLayout_6.addWidget(self.dutIPLabel, 2, 0, 1, 1)
        self.dutPw = QtWidgets.QLineEdit(self.centralwidget)
        self.dutPw.setObjectName("dutPw")
        self.DutInfoLayout_6.addWidget(self.dutPw, 4, 1, 1, 1)
        self.logOpenButton = QtWidgets.QPushButton(self.centralwidget)
        self.logOpenButton.setEnabled(False)
        self.logOpenButton.setObjectName("logOpenButton")
        self.DutInfoLayout_6.addWidget(self.logOpenButton, 4, 2, 1, 1)
        self.dutPwLabel = QtWidgets.QLabel(self.centralwidget)
        self.dutPwLabel.setObjectName("dutPwLabel")
        self.DutInfoLayout_6.addWidget(self.dutPwLabel, 4, 0, 1, 1, QtCore.Qt.AlignRight)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setEnabled(False)
        self.stopButton.setObjectName("stopButton")
        self.DutInfoLayout_6.addWidget(self.stopButton, 3, 2, 1, 1)
        self.dutUnLabel = QtWidgets.QLabel(self.centralwidget)
        self.dutUnLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dutUnLabel.setObjectName("dutUnLabel")
        self.DutInfoLayout_6.addWidget(self.dutUnLabel, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.horizontalLayout_2.addLayout(self.DutInfoLayout_6)
        self.verticalLayout_Left.addLayout(self.horizontalLayout_2)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_Left.addWidget(self.line_7)
        self.horizontalLayout.addLayout(self.verticalLayout_Left)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.actTab = QtWidgets.QWidget()
        self.actTab.setObjectName("actTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.actTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_Right = QtWidgets.QVBoxLayout()
        self.verticalLayout_Right.setObjectName("verticalLayout_Right")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_6 = QtWidgets.QFrame(self.actTab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 7, 0, 1, 5)
        self.label_3 = QtWidgets.QLabel(self.actTab)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 5)
        self.mainTimes = QtWidgets.QSpinBox(self.actTab)
        self.mainTimes.setEnabled(False)
        self.mainTimes.setMinimum(1)
        self.mainTimes.setMaximum(999999999)
        self.mainTimes.setProperty("value", 1)
        self.mainTimes.setObjectName("mainTimes")
        self.gridLayout_2.addWidget(self.mainTimes, 4, 1, 1, 1)
        self.isInfinitely = QtWidgets.QCheckBox(self.actTab)
        self.isInfinitely.setChecked(True)
        self.isInfinitely.setObjectName("isInfinitely")
        self.gridLayout_2.addWidget(self.isInfinitely, 4, 2, 1, 1)
        self.isFailCollectCB = QtWidgets.QCheckBox(self.actTab)
        self.isFailCollectCB.setChecked(True)
        self.isFailCollectCB.setObjectName("isFailCollectCB")
        self.gridLayout_2.addWidget(self.isFailCollectCB, 5, 1, 1, 1)
        self.isFailStopCB = QtWidgets.QCheckBox(self.actTab)
        self.isFailStopCB.setChecked(True)
        self.isFailStopCB.setObjectName("isFailStopCB")
        self.gridLayout_2.addWidget(self.isFailStopCB, 5, 2, 1, 1)
        self.waitForMain = QtWidgets.QSpinBox(self.actTab)
        self.waitForMain.setMaximum(1440)
        self.waitForMain.setObjectName("waitForMain")
        self.gridLayout_2.addWidget(self.waitForMain, 6, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.actTab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 4, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.actTab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.actTab)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 6, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.actTab)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 6, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.actTab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 0, 0, 1, 5)
        self.line_10 = QtWidgets.QFrame(self.actTab)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_2.addWidget(self.line_10, 2, 0, 1, 5)
        self.label_20 = QtWidgets.QLabel(self.actTab)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 3, 0, 1, 1)
        self.descriptionLineEdit = QtWidgets.QLineEdit(self.actTab)
        self.descriptionLineEdit.setObjectName("descriptionLineEdit")
        self.gridLayout_2.addWidget(self.descriptionLineEdit, 3, 1, 1, 3)
        self.verticalLayout_Right.addLayout(self.gridLayout_2)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.actDelBtn = QtWidgets.QPushButton(self.actTab)
        self.actDelBtn.setObjectName("actDelBtn")
        self.gridLayout_9.addWidget(self.actDelBtn, 0, 1, 1, 1)
        self.actMvDownBtn = QtWidgets.QPushButton(self.actTab)
        self.actMvDownBtn.setObjectName("actMvDownBtn")
        self.gridLayout_9.addWidget(self.actMvDownBtn, 0, 3, 1, 1)
        self.actAddBtn = QtWidgets.QPushButton(self.actTab)
        self.actAddBtn.setObjectName("actAddBtn")
        self.gridLayout_9.addWidget(self.actAddBtn, 0, 0, 1, 1)
        self.actMvUpBtn = QtWidgets.QPushButton(self.actTab)
        self.actMvUpBtn.setObjectName("actMvUpBtn")
        self.gridLayout_9.addWidget(self.actMvUpBtn, 0, 2, 1, 1)
        self.actClrBtn = QtWidgets.QPushButton(self.actTab)
        self.actClrBtn.setObjectName("actClrBtn")
        self.gridLayout_9.addWidget(self.actClrBtn, 0, 4, 1, 1)
        self.verticalLayout_Right.addLayout(self.gridLayout_9)
        self.actTableWidget = QtWidgets.QTableWidget(self.actTab)
        self.actTableWidget.setAcceptDrops(True)
        self.actTableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.actTableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.actTableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.actTableWidget.setMidLineWidth(0)
        self.actTableWidget.setAlternatingRowColors(False)
        self.actTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.actTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.actTableWidget.setShowGrid(True)
        self.actTableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.actTableWidget.setObjectName("actTableWidget")
        self.actTableWidget.setColumnCount(5)
        self.actTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.actTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.actTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.actTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.actTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.actTableWidget.setHorizontalHeaderItem(4, item)
        self.actTableWidget.horizontalHeader().setVisible(True)
        self.actTableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.actTableWidget.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_Right.addWidget(self.actTableWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.actTab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.feiShuLink = QtWidgets.QLineEdit(self.actTab)
        self.feiShuLink.setObjectName("feiShuLink")
        self.horizontalLayout_4.addWidget(self.feiShuLink)
        self.verticalLayout_Right.addLayout(self.horizontalLayout_4)
        self.line_8 = QtWidgets.QFrame(self.actTab)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_Right.addWidget(self.line_8)
        self.gridLayout_3.addLayout(self.verticalLayout_Right, 0, 0, 1, 1)
        self.tabWidget.addTab(self.actTab, "")
        self.areaTab = QtWidgets.QWidget()
        self.areaTab.setObjectName("areaTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.areaTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_Right_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_Right_2.setObjectName("verticalLayout_Right_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.getAreaTupleBtn = QtWidgets.QPushButton(self.areaTab)
        self.getAreaTupleBtn.setObjectName("getAreaTupleBtn")
        self.gridLayout_4.addWidget(self.getAreaTupleBtn, 6, 3, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.areaTab)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_4.addWidget(self.line_11, 0, 0, 1, 4)
        self.label_23 = QtWidgets.QLabel(self.areaTab)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 4, 0, 1, 4)
        self.line_12 = QtWidgets.QFrame(self.areaTab)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_4.addWidget(self.line_12, 3, 0, 1, 4)
        self.areaDelBtn = QtWidgets.QPushButton(self.areaTab)
        self.areaDelBtn.setObjectName("areaDelBtn")
        self.gridLayout_4.addWidget(self.areaDelBtn, 6, 1, 1, 1)
        self.areaAddBtn = QtWidgets.QPushButton(self.areaTab)
        self.areaAddBtn.setObjectName("areaAddBtn")
        self.gridLayout_4.addWidget(self.areaAddBtn, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.areaTab)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 4)
        self.areaClrBtn = QtWidgets.QPushButton(self.areaTab)
        self.areaClrBtn.setObjectName("areaClrBtn")
        self.gridLayout_4.addWidget(self.areaClrBtn, 6, 2, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.areaTab)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_4.addWidget(self.line_15, 5, 0, 1, 4)
        self.verticalLayout_Right_2.addLayout(self.gridLayout_4)
        self.areaTableWidget = QtWidgets.QTableWidget(self.areaTab)
        self.areaTableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.areaTableWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.areaTableWidget.setObjectName("areaTableWidget")
        self.areaTableWidget.setColumnCount(6)
        self.areaTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.areaTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.areaTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.areaTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.areaTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.areaTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.areaTableWidget.setHorizontalHeaderItem(5, item)
        self.areaTableWidget.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_Right_2.addWidget(self.areaTableWidget)
        self.line_13 = QtWidgets.QFrame(self.areaTab)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_Right_2.addWidget(self.line_13)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_Right_2.addLayout(self.horizontalLayout_3)
        self.gridLayout_5.addLayout(self.verticalLayout_Right_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.areaTab, "")
        self.dutMonitor = QtWidgets.QWidget()
        self.dutMonitor.setObjectName("dutMonitor")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.dutMonitor)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_29 = QtWidgets.QLabel(self.dutMonitor)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.dutMonitor, "")
        self.ocrTestTab = QtWidgets.QWidget()
        self.ocrTestTab.setObjectName("ocrTestTab")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.ocrTestTab)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.line_17 = QtWidgets.QFrame(self.ocrTestTab)
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_12.addWidget(self.line_17, 0, 0, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_46 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.gridLayout_11.addWidget(self.label_46, 16, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.gridLayout_11.addWidget(self.label_41, 13, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.gridLayout_11.addWidget(self.label_39, 20, 0, 1, 1)
        self.line_18 = QtWidgets.QFrame(self.ocrTestTab)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_11.addWidget(self.line_18, 25, 0, 1, 4)
        self.label_45 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_45.setText("")
        self.label_45.setObjectName("label_45")
        self.gridLayout_11.addWidget(self.label_45, 17, 0, 1, 1)
        self.ocrTestGetTupleBtn = QtWidgets.QPushButton(self.ocrTestTab)
        self.ocrTestGetTupleBtn.setObjectName("ocrTestGetTupleBtn")
        self.gridLayout_11.addWidget(self.ocrTestGetTupleBtn, 1, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.gridLayout_11.addWidget(self.label_42, 12, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_44.setObjectName("label_44")
        self.gridLayout_11.addWidget(self.label_44, 3, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_30.setObjectName("label_30")
        self.gridLayout_11.addWidget(self.label_30, 1, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_32.setObjectName("label_32")
        self.gridLayout_11.addWidget(self.label_32, 5, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.gridLayout_11.addWidget(self.label_38, 21, 0, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.ocrTestTab)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout_11.addWidget(self.line_21, 6, 0, 1, 4)
        self.ocrTestPictureLabel = QtWidgets.QLabel(self.ocrTestTab)
        self.ocrTestPictureLabel.setText("")
        self.ocrTestPictureLabel.setObjectName("ocrTestPictureLabel")
        self.gridLayout_11.addWidget(self.ocrTestPictureLabel, 5, 1, 1, 2)
        self.label_37 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.gridLayout_11.addWidget(self.label_37, 23, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.gridLayout_11.addWidget(self.label_33, 9, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_35.setObjectName("label_35")
        self.gridLayout_11.addWidget(self.label_35, 7, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.gridLayout_11.addWidget(self.label_49, 14, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.gridLayout_11.addWidget(self.label_36, 22, 0, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.ocrTestTab)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_11.addWidget(self.line_14, 0, 0, 1, 4)
        self.label_43 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.gridLayout_11.addWidget(self.label_43, 11, 0, 1, 1)
        self.line_22 = QtWidgets.QFrame(self.ocrTestTab)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.gridLayout_11.addWidget(self.line_22, 8, 0, 1, 4)
        self.label_31 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.gridLayout_11.addWidget(self.label_31, 19, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.gridLayout_11.addWidget(self.label_40, 18, 0, 1, 1)
        self.ocrTestBtn = QtWidgets.QPushButton(self.ocrTestTab)
        self.ocrTestBtn.setObjectName("ocrTestBtn")
        self.gridLayout_11.addWidget(self.ocrTestBtn, 1, 3, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_47.setText("")
        self.label_47.setObjectName("label_47")
        self.gridLayout_11.addWidget(self.label_47, 15, 0, 1, 1)
        self.ocrTestResultLineEdit = QtWidgets.QLineEdit(self.ocrTestTab)
        self.ocrTestResultLineEdit.setReadOnly(True)
        self.ocrTestResultLineEdit.setObjectName("ocrTestResultLineEdit")
        self.gridLayout_11.addWidget(self.ocrTestResultLineEdit, 7, 1, 1, 2)
        self.psmCombox = QtWidgets.QComboBox(self.ocrTestTab)
        self.psmCombox.setObjectName("psmCombox")
        self.gridLayout_11.addWidget(self.psmCombox, 1, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.gridLayout_11.addWidget(self.label_48, 10, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.ocrTestTab)
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.gridLayout_11.addWidget(self.label_34, 24, 0, 1, 1)
        self.line_20 = QtWidgets.QFrame(self.ocrTestTab)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout_11.addWidget(self.line_20, 4, 0, 1, 4)
        self.line_23 = QtWidgets.QFrame(self.ocrTestTab)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.gridLayout_11.addWidget(self.line_23, 2, 0, 1, 4)
        self.ocrTupleLineEdit = QtWidgets.QLineEdit(self.ocrTestTab)
        self.ocrTupleLineEdit.setObjectName("ocrTupleLineEdit")
        self.gridLayout_11.addWidget(self.ocrTupleLineEdit, 3, 1, 1, 2)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 1, 1, 1)
        self.line_19 = QtWidgets.QFrame(self.ocrTestTab)
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout_12.addWidget(self.line_19, 0, 2, 1, 1)
        self.tabWidget.addTab(self.ocrTestTab, "")
        self.OtherTab = QtWidgets.QWidget()
        self.OtherTab.setObjectName("OtherTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.OtherTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.MemoryErrorThreshold = QtWidgets.QDoubleSpinBox(self.OtherTab)
        self.MemoryErrorThreshold.setDecimals(1)
        self.MemoryErrorThreshold.setMaximum(100.0)
        self.MemoryErrorThreshold.setProperty("value", 75.0)
        self.MemoryErrorThreshold.setObjectName("MemoryErrorThreshold")
        self.gridLayout_7.addWidget(self.MemoryErrorThreshold, 9, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.OtherTab)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 12, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.OtherTab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 5, 2, 1, 1)
        self.dutCfgFrLE = QtWidgets.QLineEdit(self.OtherTab)
        self.dutCfgFrLE.setText("")
        self.dutCfgFrLE.setReadOnly(True)
        self.dutCfgFrLE.setObjectName("dutCfgFrLE")
        self.gridLayout_7.addWidget(self.dutCfgFrLE, 2, 1, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.OtherTab)
        self.label_25.setObjectName("label_25")
        self.gridLayout_7.addWidget(self.label_25, 10, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.OtherTab)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 9, 0, 1, 1)
        self.dutCfgFrBtn = QtWidgets.QToolButton(self.OtherTab)
        self.dutCfgFrBtn.setObjectName("dutCfgFrBtn")
        self.gridLayout_7.addWidget(self.dutCfgFrBtn, 2, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.OtherTab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 6, 0, 1, 1)
        self.reloadRcTime = QtWidgets.QSpinBox(self.OtherTab)
        self.reloadRcTime.setMinimum(300)
        self.reloadRcTime.setMaximum(600)
        self.reloadRcTime.setObjectName("reloadRcTime")
        self.gridLayout_7.addWidget(self.reloadRcTime, 6, 1, 1, 1)
        self.momWlFnLE = QtWidgets.QLineEdit(self.OtherTab)
        self.momWlFnLE.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.momWlFnLE.setText("")
        self.momWlFnLE.setReadOnly(True)
        self.momWlFnLE.setObjectName("momWlFnLE")
        self.gridLayout_7.addWidget(self.momWlFnLE, 4, 1, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.OtherTab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 6, 2, 1, 1)
        self.EMMCErrorThreshold = QtWidgets.QSpinBox(self.OtherTab)
        self.EMMCErrorThreshold.setMaximum(100)
        self.EMMCErrorThreshold.setProperty("value", 85)
        self.EMMCErrorThreshold.setObjectName("EMMCErrorThreshold")
        self.gridLayout_7.addWidget(self.EMMCErrorThreshold, 11, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.OtherTab)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 9, 2, 1, 1)
        self.momWlFnBtn = QtWidgets.QToolButton(self.OtherTab)
        self.momWlFnBtn.setObjectName("momWlFnBtn")
        self.gridLayout_7.addWidget(self.momWlFnBtn, 4, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.OtherTab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 5, 0, 1, 1)
        self.reduRcTime = QtWidgets.QSpinBox(self.OtherTab)
        self.reduRcTime.setMinimum(30)
        self.reduRcTime.setMaximum(300)
        self.reduRcTime.setObjectName("reduRcTime")
        self.gridLayout_7.addWidget(self.reduRcTime, 5, 1, 1, 1)
        self.CPUErrorThreshold = QtWidgets.QDoubleSpinBox(self.OtherTab)
        self.CPUErrorThreshold.setDecimals(1)
        self.CPUErrorThreshold.setProperty("value", 75.0)
        self.CPUErrorThreshold.setObjectName("CPUErrorThreshold")
        self.gridLayout_7.addWidget(self.CPUErrorThreshold, 10, 1, 1, 1)
        self.logMaxNum = QtWidgets.QSpinBox(self.OtherTab)
        self.logMaxNum.setMinimum(1000)
        self.logMaxNum.setMaximum(20000)
        self.logMaxNum.setProperty("value", 5000)
        self.logMaxNum.setObjectName("logMaxNum")
        self.gridLayout_7.addWidget(self.logMaxNum, 12, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.OtherTab)
        self.label_27.setObjectName("label_27")
        self.gridLayout_7.addWidget(self.label_27, 11, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.OtherTab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.OtherTab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.OtherTab)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 14, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.OtherTab)
        self.label_24.setObjectName("label_24")
        self.gridLayout_7.addWidget(self.label_24, 10, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.OtherTab)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 12, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.OtherTab)
        self.label_26.setObjectName("label_26")
        self.gridLayout_7.addWidget(self.label_26, 11, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.OtherTab)
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.gridLayout_7.addWidget(self.label_28, 13, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_7)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.OtherTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        OCR_UI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OCR_UI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 23))
        self.menubar.setObjectName("menubar")
        self.configMenu = QtWidgets.QMenu(self.menubar)
        self.configMenu.setObjectName("configMenu")
        self.tipMenu = QtWidgets.QMenu(self.menubar)
        self.tipMenu.setObjectName("tipMenu")
        self.aboutMenu = QtWidgets.QMenu(self.menubar)
        self.aboutMenu.setObjectName("aboutMenu")
        OCR_UI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OCR_UI)
        self.statusbar.setObjectName("statusbar")
        OCR_UI.setStatusBar(self.statusbar)
        self.configInput = QtWidgets.QAction(OCR_UI)
        self.configInput.setShortcutContext(QtCore.Qt.WidgetWithChildrenShortcut)
        self.configInput.setObjectName("configInput")
        self.configOutput = QtWidgets.QAction(OCR_UI)
        self.configOutput.setObjectName("configOutput")
        self.action_2 = QtWidgets.QAction(OCR_UI)
        self.action_2.setObjectName("action_2")
        self.OCRTip = QtWidgets.QAction(OCR_UI)
        self.OCRTip.setObjectName("OCRTip")
        self.action = QtWidgets.QAction(OCR_UI)
        self.action.setObjectName("action")
        self.action_3 = QtWidgets.QAction(OCR_UI)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(OCR_UI)
        self.action_4.setObjectName("action_4")
        self.steadyMode = QtWidgets.QAction(OCR_UI)
        self.steadyMode.setObjectName("steadyMode")
        self.unsteadyMode = QtWidgets.QAction(OCR_UI)
        self.unsteadyMode.setObjectName("unsteadyMode")
        self.actionMode = QtWidgets.QAction(OCR_UI)
        self.actionMode.setObjectName("actionMode")
        self.areaInput = QtWidgets.QAction(OCR_UI)
        self.areaInput.setObjectName("areaInput")
        self.areaOutput = QtWidgets.QAction(OCR_UI)
        self.areaOutput.setObjectName("areaOutput")
        self.whiteListTip = QtWidgets.QAction(OCR_UI)
        self.whiteListTip.setObjectName("whiteListTip")
        self.informationAbout = QtWidgets.QAction(OCR_UI)
        self.informationAbout.setObjectName("informationAbout")
        self.configMenu.addAction(self.configInput)
        self.configMenu.addAction(self.configOutput)
        self.configMenu.addSeparator()
        self.configMenu.addAction(self.areaInput)
        self.configMenu.addAction(self.areaOutput)
        self.configMenu.addSeparator()
        self.tipMenu.addAction(self.OCRTip)
        self.tipMenu.addAction(self.whiteListTip)
        self.aboutMenu.addAction(self.informationAbout)
        self.menubar.addAction(self.configMenu.menuAction())
        self.menubar.addAction(self.tipMenu.menuAction())
        self.menubar.addAction(self.aboutMenu.menuAction())
        self.dutIPLabel.setBuddy(self.dutIP)
        self.dutPwLabel.setBuddy(self.dutPw)
        self.dutUnLabel.setBuddy(self.dutUn)

        self.retranslateUi(OCR_UI)
        self.tabWidget.setCurrentIndex(0)
        self.isInfinitely.toggled['bool'].connect(self.mainTimes.setDisabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(OCR_UI)
        OCR_UI.setTabOrder(self.dutIP, self.dutUn)
        OCR_UI.setTabOrder(self.dutUn, self.dutPw)
        OCR_UI.setTabOrder(self.dutPw, self.logText)

    def retranslateUi(self, OCR_UI):
        _translate = QtCore.QCoreApplication.translate
        OCR_UI.setWindowTitle(_translate("OCR_UI", "拷机工具_V2.34"))
        self.StatusLabel.setText(_translate("OCR_UI", "未运行"))
        self.label.setText(_translate("OCR_UI", "设备信息"))
        self.label_2.setText(_translate("OCR_UI", "实时Log"))
        self.label_15.setText(_translate("OCR_UI", "当前状态 ："))
        self.beginButton.setText(_translate("OCR_UI", "开 始"))
        self.dutIPLabel.setText(_translate("OCR_UI", "IP："))
        self.logOpenButton.setText(_translate("OCR_UI", "打开Log文件"))
        self.dutPwLabel.setText(_translate("OCR_UI", "Password："))
        self.stopButton.setText(_translate("OCR_UI", "停 止"))
        self.dutUnLabel.setText(_translate("OCR_UI", "Username："))
        self.label_3.setText(_translate("OCR_UI", "拷机设置"))
        self.isInfinitely.setText(_translate("OCR_UI", "不限次数"))
        self.isFailCollectCB.setText(_translate("OCR_UI", "一键收集"))
        self.isFailStopCB.setText(_translate("OCR_UI", "停止拷机"))
        self.label_14.setText(_translate("OCR_UI", "拷机轮次："))
        self.label_12.setText(_translate("OCR_UI", "检查项Fail时："))
        self.label_18.setText(_translate("OCR_UI", "拷机开始时间："))
        self.label_19.setText(_translate("OCR_UI", "min后 (取值范围 0 - 1440)"))
        self.label_20.setText(_translate("OCR_UI", "拷机描述："))
        self.descriptionLineEdit.setPlaceholderText(_translate("OCR_UI", "必填，用于统计用例PASS率"))
        self.actDelBtn.setText(_translate("OCR_UI", "删除"))
        self.actMvDownBtn.setText(_translate("OCR_UI", "下移"))
        self.actAddBtn.setText(_translate("OCR_UI", "添加"))
        self.actMvUpBtn.setText(_translate("OCR_UI", "上移"))
        self.actClrBtn.setText(_translate("OCR_UI", "清空"))
        item = self.actTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("OCR_UI", "动作"))
        item = self.actTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("OCR_UI", "参数1"))
        item = self.actTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("OCR_UI", "参数2"))
        item = self.actTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("OCR_UI", "执行次数"))
        item = self.actTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("OCR_UI", "等待时间(s)"))
        self.label_10.setText(_translate("OCR_UI", "飞书告警链接："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.actTab), _translate("OCR_UI", "拷机设置"))
        self.getAreaTupleBtn.setText(_translate("OCR_UI", "坐标获取"))
        self.label_23.setText(_translate("OCR_UI", "注：在【拷机设置】中添加\"[检查项]测试仪数值\"项,执行至该项时,开始以下区域监控"))
        self.areaDelBtn.setText(_translate("OCR_UI", "删除"))
        self.areaAddBtn.setText(_translate("OCR_UI", "添加"))
        self.label_4.setText(_translate("OCR_UI", "区域设置"))
        self.areaClrBtn.setText(_translate("OCR_UI", "清空"))
        item = self.areaTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("OCR_UI", "坐标值"))
        item = self.areaTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("OCR_UI", "与预期关系"))
        item = self.areaTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("OCR_UI", "预期值"))
        item = self.areaTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("OCR_UI", "备注(可选)"))
        item = self.areaTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("OCR_UI", "区域截图"))
        item = self.areaTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("OCR_UI", "识别结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.areaTab), _translate("OCR_UI", "区域设置"))
        self.label_29.setText(_translate("OCR_UI", "未开放"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dutMonitor), _translate("OCR_UI", "设备监控"))
        self.ocrTestGetTupleBtn.setText(_translate("OCR_UI", "获取坐标"))
        self.label_44.setText(_translate("OCR_UI", "坐标值"))
        self.label_30.setText(_translate("OCR_UI", "psm参数值"))
        self.label_32.setText(_translate("OCR_UI", "区域截图"))
        self.label_35.setText(_translate("OCR_UI", "识别结果"))
        self.ocrTestBtn.setText(_translate("OCR_UI", "开始识别"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ocrTestTab), _translate("OCR_UI", "OCR识别测试"))
        self.label_22.setText(_translate("OCR_UI", "(取值范围 1000 - 20000)"))
        self.label_8.setText(_translate("OCR_UI", "(取值范围 30 - 300)"))
        self.label_25.setText(_translate("OCR_UI", "% (大于该值则认为有异常)"))
        self.label_16.setText(_translate("OCR_UI", "线卡内存异常阈值："))
        self.dutCfgFrBtn.setText(_translate("OCR_UI", "..."))
        self.label_9.setText(_translate("OCR_UI", "整机重启重连等待时间(s)："))
        self.label_11.setText(_translate("OCR_UI", "(取值范围 300 - 600)"))
        self.label_17.setText(_translate("OCR_UI", "% (大于该值则认为有异常)"))
        self.momWlFnBtn.setText(_translate("OCR_UI", "..."))
        self.label_7.setText(_translate("OCR_UI", "主备切换重连等待时间(s)："))
        self.label_27.setText(_translate("OCR_UI", "% (小于该值则认为有异常)"))
        self.label_13.setText(_translate("OCR_UI", "0消息白名单文件路径："))
        self.label_6.setText(_translate("OCR_UI", "设备配置文件夹路径："))
        self.label_24.setText(_translate("OCR_UI", "线卡CPU异常阈值："))
        self.label_21.setText(_translate("OCR_UI", "实时log最大保存行数："))
        self.label_26.setText(_translate("OCR_UI", "线卡EMMC寿命异常阈值："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OtherTab), _translate("OCR_UI", "其他设置"))
        self.configMenu.setTitle(_translate("OCR_UI", "导入/导出"))
        self.tipMenu.setTitle(_translate("OCR_UI", "使用说明"))
        self.aboutMenu.setTitle(_translate("OCR_UI", "关于"))
        self.configInput.setText(_translate("OCR_UI", "导入拷机设置\n"
""))
        self.configOutput.setText(_translate("OCR_UI", "导出拷机设置"))
        self.action_2.setText(_translate("OCR_UI", "白名单格式说明"))
        self.OCRTip.setText(_translate("OCR_UI", "监控说明"))
        self.action.setText(_translate("OCR_UI", "稳态切换"))
        self.action_3.setText(_translate("OCR_UI", "非稳态切换"))
        self.action_4.setText(_translate("OCR_UI", "故障注入后切换"))
        self.steadyMode.setText(_translate("OCR_UI", "稳态切换"))
        self.unsteadyMode.setText(_translate("OCR_UI", "非稳态切换"))
        self.actionMode.setText(_translate("OCR_UI", "故障注入后切换"))
        self.areaInput.setText(_translate("OCR_UI", "导入监控设置"))
        self.areaOutput.setText(_translate("OCR_UI", "导出监控设置"))
        self.whiteListTip.setText(_translate("OCR_UI", "白名单"))
        self.informationAbout.setText(_translate("OCR_UI", "软件信息"))

    # def zdy(self):
        self.psmCombox.addItems(['6','7','8'])
        self.ocrTestPictureLabel.setScaledContents(True)
        self.dutCfgFrLE.setText(dftDutCfgFr)
        self.momWlFnLE.setText(dftmomWlFn)
        self.actTableWidget.verticalHeader
        self.actTableWidget.setColumnWidth(0, 180)
        self.actTableWidget.setColumnWidth(1, 90)
        self.actTableWidget.setColumnWidth(2, 90)
        self.actTableWidget.setColumnWidth(3, 75)
        self.actTableWidget.setColumnWidth(4, 70)
        self.areaTableWidget.setColumnWidth(0, 135)
        self.actAddBtn.clicked.connect(self.actAdd)
        self.actDelBtn.clicked.connect(self.actDel)
        self.actClrBtn.clicked.connect(self.actClr)
        self.beginButton.clicked.connect(self.logText.clear)
        self.stopButton.clicked.connect(self.stopMain)
        self.beginButton.clicked.connect(self.runMain)
        self.actMvUpBtn.clicked.connect(self.actMvUp)
        self.actMvDownBtn.clicked.connect(self.actMvDown)
        self.areaAddBtn.clicked.connect(self.areaAdd)
        self.areaDelBtn.clicked.connect(self.areaDel)
        self.areaClrBtn.clicked.connect(self.areaClr)
        self.getAreaTupleBtn.clicked.connect(self.getAreaTp)
        self.ocrTestGetTupleBtn.clicked.connect(self.getAreaTp)
        self.dutCfgFrBtn.clicked.connect(self.dutCfgFrLEInput)
        self.momWlFnBtn.clicked.connect(self.momWlFnInput)
        self.logOpenButton.clicked.connect(self.openLog)
        self.configOutput.triggered.connect(self.outputInfo)
        self.configInput.triggered.connect(self.inputInfo)
        self.areaInput.triggered.connect(self.inputArea)
        self.areaOutput.triggered.connect(self.outputArea)
        self.informationAbout.triggered.connect(self.openInfoQbox)
        self.OCRTip.triggered.connect(self.openUrlOcrTip)
        self.whiteListTip.triggered.connect(self.openUrlwhiteListTip)
        self.ocrTestBtn.clicked.connect(self.runOcrTest)

    #log重定向   
    def outputWritten(self, text):
        cursor = self.logText.textCursor() #获得指针对象
        cursor.movePosition(QtGui.QTextCursor.End)
        cursor.insertText(text)
        self.logText.setTextCursor(cursor)
        self.logText.ensureCursorVisible()

    #拷机参数表格操作
    def actAdd(self):
        try: 
            row = self.actTableWidget.currentRow() #获取当前选中行
            self.actTableWidget.insertRow(row+1) #在当前选中行的下一行添加新行（默认为主备切换）
            self.actTableWidget.setCellWidget(row+1, 0, actionCombox(self.actionChanged))
            self.actTableWidget.setCellWidget(row+1, 1, myLineEdit())
            self.actTableWidget.setCellWidget(row+1, 2, myLineEdit())
            self.actTableWidget.setCellWidget(row+1, 3, actTimesSpinBox())
            self.actTableWidget.setCellWidget(row+1, 4, waitTimeLineEdit())
        except Exception as e:
            print(e)

    def actDel(self):
        row = self.actTableWidget.currentRow() #获取当前选中行
        self.actTableWidget.removeRow(row) #删除当前行
        self.actTableWidget.selectRow(-1) #选中新行

    def actClr(self):
        self.actTableWidget.setRowCount(0)
        self.actTableWidget.clearContents()

    def actMvDown(self):
        try:
            if self.actTableWidget.rowCount() == 1:
                return
            row = self.actTableWidget.currentRow()
            column = self.actTableWidget.currentColumn()
            
            if row < self.actTableWidget.rowCount()-1:
                #print(row)
                actionName  = self.actTableWidget.cellWidget(row,0)
                arg1 = self.actTableWidget.cellWidget(row,1)
                arg2 = self.actTableWidget.cellWidget(row,2)
                times = self.actTableWidget.cellWidget(row,3)
                wt = self.actTableWidget.cellWidget(row,4)
                self.actTableWidget.insertRow(row+2)
                #第一列
                self.actTableWidget.setCellWidget(row+2,0,actionName)
                #self.actTableWidget.cellWidget(row+2,0).setCurrentText(actionName)
                #第二列
                self.actTableWidget.setCellWidget(row+2,1,arg1)
                #self.actTableWidget.cellWidget(row+2,1).setText(arg1)
                #第三列
                self.actTableWidget.setCellWidget(row+2,2,arg2)
                #self.actTableWidget.cellWidget(row+2,2).setText(arg2)
                #第四列
                self.actTableWidget.setCellWidget(row+2,3,times)
                self.actTableWidget.setCellWidget(row+2,4,wt)
                #self.actTableWidget.cellWidget(row+2,3).setText(wt)
                #选中行
                self.actTableWidget.setCurrentCell(row+2,column)
                #删除原先行
                self.actTableWidget.removeRow(row)  
        except Exception as e:
            print(e)

    def actMvUp(self):
        try:
            row = self.actTableWidget.currentRow()
            column = self.actTableWidget.currentColumn()
            if row > 0:
                actionName  = self.actTableWidget.cellWidget(row,0)
                arg1 = self.actTableWidget.cellWidget(row,1)
                arg2 = self.actTableWidget.cellWidget(row,2)
                times = self.actTableWidget.cellWidget(row,3)
                wt = self.actTableWidget.cellWidget(row,4)
                self.actTableWidget.insertRow(row-1)
                #第一列
                self.actTableWidget.setCellWidget(row-1,0,actionName)
                #self.actTableWidget.cellWidget(row-1,0).setCurrentText(actionName)
                #第二列
                self.actTableWidget.setCellWidget(row-1,1,arg1)
                #self.actTableWidget.cellWidget(row-1,1).setText(arg1)
                #第三列
                self.actTableWidget.setCellWidget(row-1,2,arg2)
                #self.actTableWidget.cellWidget(row-1,2).setText(arg2)
                #第四列
                self.actTableWidget.setCellWidget(row-1,3,times)
                self.actTableWidget.setCellWidget(row-1,4,wt)
                #self.actTableWidget.cellWidget(row-1,3).setText(wt)
                #选中行
                self.actTableWidget.setCurrentCell(row-1,column)
                #删除原先行
                self.actTableWidget.removeRow(row+1)
        except Exception as e:
            print(e)

    #监控区域表格操作
    def areaAdd(self):
        try:
            row = self.areaTableWidget.rowCount()
            self.areaTableWidget.insertRow(row)
            self.areaTableWidget.setCellWidget(row, 0, areaLineEdit())
            self.areaTableWidget.setCellWidget(row, 1, expectCombox())
            self.areaTableWidget.setCellWidget(row, 2, expectLineEdit())
            self.areaTableWidget.setCellWidget(row, 3, noteLineEdit())
            self.areaTableWidget.setCellWidget(row, 4, pictureLabel())
            self.areaTableWidget.setCellWidget(row, 5, ocrResultLineEdit())
        except Exception as e:
            print(e)

    def areaDel(self):
        row = self.areaTableWidget.currentRow()
        self.areaTableWidget.removeRow(row)
        self.areaTableWidget.selectRow(-1)

    def areaClr(self):
        self.areaTableWidget.setRowCount(0)
        self.areaTableWidget.clearContents()

    def getAreaDict(self):
        try:
            d = {}
            for i in range(self.areaTableWidget.rowCount()):
                d[i] = {
                        "areaTuple":self.areaTableWidget.cellWidget(i,0).text(),
                        "expectSec":self.areaTableWidget.cellWidget(i,1).currentText(),
                        "expectValue":self.areaTableWidget.cellWidget(i,2).text(),
                        "note":self.areaTableWidget.cellWidget(i,3).text()
                        }
            return d
        except Exception as e:
            #print(e)
            return {}
       
    def getActDict(self):
        try:
            d = {}
            for i in range(self.actTableWidget.rowCount()):
                d[i] = {
                        "action":getQwidgetValue(self.actTableWidget.cellWidget(i,0)),
                        "arg_1":getQwidgetValue(self.actTableWidget.cellWidget(i,1)),
                        "arg_2":getQwidgetValue(self.actTableWidget.cellWidget(i,2)),
                        "times":getQwidgetValue(self.actTableWidget.cellWidget(i,3)),
                        "waitFor":getQwidgetValue(self.actTableWidget.cellWidget(i,4))
                        }
            return d
        except Exception as e:
            print(e)
            return {}
        
    def getDutInfo(self):
        dutInfoDict = {}
        ipText = self.dutIP.text()
        if '-' in ipText:
            dutInfoDict['ip'] = ipText.split('-')[0]
            dutInfoDict['port'] = ipText.split('-')[1]
        else:
            dutInfoDict['ip'] = ipText
            dutInfoDict['port'] = '23'
        
        dutInfoDict["UserName"] = self.dutUn.text()
        dutInfoDict["PassWord"] = self.dutPw.text()
        #timePrint(dutInfoDict)
        return dutInfoDict
    
    def dutCfgFrLEInput(self):
        try:
            fr = QFileDialog.getExistingDirectory(None, '选择文件夹', os.getcwd())
            if fr:
                self.dutCfgFrLE.setText(fr)
        except FileNotFoundError:
            return False
        except:
            QMessageBox.warning(None,"Error！", "文件夹选择失败！", QMessageBox.Ok)
            return False

    def momWlFnInput(self):
        try:
            fn = QFileDialog.getOpenFileName(None, '选择文件', os.getcwd(),"Text Files(*.txt)")[0]
            if fn:
                self.momWlFn.setText(fn)
        except FileNotFoundError:
            return False
        except:
            QMessageBox.warning(None,"Error！", "文件选择失败！", QMessageBox.Ok)
            return False

    #所有输入框/下拉框/btn禁止输入
    @error_handler
    def disableInput(self):
        for actionCbox in self.actTableWidget.findChildren(QComboBox):
            actionCbox.setEnabled(False)
        
        for actionELine in self.actTableWidget.findChildren(myLineEdit):
            actionELine.setEnabled(False)

        for actionCheckBox in self.actTableWidget.findChildren(QCheckBox):
            actionCheckBox.setEnabled(False)

        for actionSpinBox in self.actTableWidget.findChildren(QSpinBox):
            actionSpinBox.setEnabled(False)

        for actionText in self.actTableWidget.findChildren(myTextEdit):
            actionText.setEnabled(False)

        for areaCbox in self.areaTableWidget.findChildren(QComboBox):
            areaCbox.setEnabled(False)
        
        for areaELine in self.areaTableWidget.findChildren(myLineEdit):
            areaELine.setEnabled(False)        
        #pass
        self.stopButton.setEnabled(True)
        self.beginButton.setEnabled(False)
        self.areaAddBtn.setEnabled(False)
        self.areaDelBtn.setEnabled(False)
        self.areaClrBtn.setEnabled(False)
        self.actAddBtn.setEnabled(False)
        self.actDelBtn.setEnabled(False)
        self.actClrBtn.setEnabled(False)
        self.actMvDownBtn.setEnabled(False)
        self.actMvUpBtn.setEnabled(False)
        self.getAreaTupleBtn.setEnabled(False)
        self.ocrTestGetTupleBtn.setEnabled(False)
        self.descriptionLineEdit.setEnabled(False)
        self.configInput.setEnabled(False)
        self.areaInput.setEnabled(False)
        self.descriptionLineEdit.setEnabled(False)
        self.isInfinitely.setEnabled(False)
        self.dutIP.setEnabled(False)
        self.dutPw.setEnabled(False)
        self.dutUn.setEnabled(False)
        
        #actionset
        # self.actionSet = self.getCurOption()
        self.mainTimes.setEnabled(False)
        self.isInfinitely.setEnabled(False)
        # self.isFailCollectCB.setEnabled(False)
        # self.isFailStopCB.setEnabled(False)
        self.waitForMain.setEnabled(False)
        

    #所有输入框/下拉框/btn恢复输入
    def enableInput(self):
        for actionCbox in self.actTableWidget.findChildren(QComboBox):
            actionCbox.setEnabled(True)
        
        for actionELine in self.actTableWidget.findChildren(myLineEdit):
            actionELine.setEnabled(True)

        for actionCheckBox in self.actTableWidget.findChildren(QCheckBox):
            actionCheckBox.setEnabled(True)

        for actionSpinBox in self.actTableWidget.findChildren(QSpinBox):
            actionSpinBox.setEnabled(True)

        for actionText in self.actTableWidget.findChildren(myTextEdit):
            actionText.setEnabled(True)

        for areaCbox in self.areaTableWidget.findChildren(QComboBox):
            areaCbox.setEnabled(True)
        
        for areaELine in self.areaTableWidget.findChildren(myLineEdit):
            areaELine.setEnabled(True)        

        self.stopButton.setEnabled(False)
        self.beginButton.setEnabled(True)
        self.areaAddBtn.setEnabled(True)
        self.areaDelBtn.setEnabled(True)
        self.areaClrBtn.setEnabled(True)
        self.actAddBtn.setEnabled(True)
        self.actDelBtn.setEnabled(True)
        self.actClrBtn.setEnabled(True)
        self.actMvDownBtn.setEnabled(True)
        self.actMvUpBtn.setEnabled(True)
        self.getAreaTupleBtn.setEnabled(True)
        self.ocrTestGetTupleBtn.setEnabled(True)
        self.descriptionLineEdit.setEnabled(True)
        self.configInput.setEnabled(True)
        self.areaInput.setEnabled(True)
        self.descriptionLineEdit.setEnabled(True)
        self.dutIP.setEnabled(True)
        self.dutPw.setEnabled(True)
        self.dutUn.setEnabled(True)
        # self.isFailCollectCB.setEnabled(True)
        # self.isFailStopCB.setEnabled(True)
        self.isInfinitely.setEnabled(True)
        self.waitForMain.setEnabled(True)
        if self.isInfinitely.isChecked():
            self.mainTimes.setEnabled(False)
        else:
            self.mainTimes.setEnabled(True)
        #
        
        # self.setCurOption(self.actionSet)
        # del self.actionSet


    def clearAreaResults(self):
        for row in range(len(self.getAreaDict())):
            #self.areaTableWidget.setCellWidget()
            self.areaTableWidget.setCellWidget(row, 4, pictureLabel())
            self.areaTableWidget.setCellWidget(row, 5, ocrResultLineEdit())
    
    #打开日志
    @error_handler
    def openLog(self):
        logFn = self.logFn
        def fun():
            os.popen(logFn)
        self.openLogThread = MainThread(target=fun)
        self.openLogThread.start()
        
    
    #日志导出
    def saveLog(self):
        logTxt = self.logText.toPlainText()
        try:
            logLs = []
            ls = logTxt.splitlines()
            for line in ls:
                if line:
                    logLs.append(line)
            fn = QtWidgets.QFileDialog.getSaveFileName(None, 'Save as', os.getcwd(),"Text Files(*.log)")[0]
            writeListTxt(logLs,fn)
            QMessageBox.information(None, "Comlete！", "Log导出完成！", QMessageBox.Ok)
            return True
        except FileNotFoundError:
            return False
        except BaseException:
            QMessageBox.warning(None,"Error！", "Log导出失败！", QMessageBox.Ok)
            return False

    #参数导出
    @error_handler
    def outputInfo(self):
        fn = QtWidgets.QFileDialog.getSaveFileName(None, 'Save as', os.getcwd(),"Text Files(*.kjcfg)")[0]
        dutInfo = self.getDutInfo()
        actInfo = self.getActDict()

        try:
            actSet = self.actionSet
        except:
            actSet = self.getCurOption()
        
        try:
            with open(fn,"w+") as f:
                f.write(str(dutInfo)+'\n' + 
                        str(actInfo)+'\n' +
                        str(actSet) +'\n')
            QMessageBox.information(None, "Comlete！", "参数导出完成！", QMessageBox.Ok)
            #return True
        except FileNotFoundError:
            return False
        except BaseException:
            QMessageBox.warning(None,"Error！", "参数导出失败！", QMessageBox.Ok)
            #return False
        except Exception as e:
            print(e)

    #参数导入
    @error_handler
    def inputInfo(self):
        fn = QtWidgets.QFileDialog.getOpenFileName(None, 'Open File', os.getcwd(),"Text Files(*.kjcfg)")[0]
        try:
            with open(fn,"r+") as f:
                ls = f.read().split('\n')
            dutInfo = eval(ls[0])
            actionInfo = eval(ls[1])
            actionSet = eval(ls[2])
            #设备信息
            if dutInfo.get('port') == "23":
                self.dutIP.setText(dutInfo['ip'])
            else:
                self.dutIP.setText(f"{dutInfo['ip']}-{dutInfo['port']}")
            self.dutUn.setText(dutInfo['UserName'])
            self.dutPw.setText(dutInfo['PassWord'])
            #拷机动作
            self.actClr()
            for k,v in actionInfo.items():
                self.actTableWidget.insertRow(k)
                actionName  = v.get('action')
                arg1 = v.get('arg_1')
                arg2 = v.get('arg_2')
                times = v.get('times')
                wt = v.get('waitFor')

                #第一列
                self.actTableWidget.setCellWidget(k,0,actionCombox(self.actionChanged))
                self.actTableWidget.cellWidget(k,0).setCurrentText(actionName)
                
                #第二/第三列
                self.actTableWidget.setCellWidget(k,1,eval(actionArgs.get(actionName).get('arg1')))
                self.actTableWidget.setCellWidget(k,2,eval(actionArgs.get(actionName).get('arg2')))
                
                setQwidgetValue(self.actTableWidget.cellWidget(k,1),arg1)
                setQwidgetValue(self.actTableWidget.cellWidget(k,2),arg2)
                #tip & holder
                try:
                    self.actTableWidget.cellWidget(k,1).setPlaceholderText(actionTips.get(actionName).get('holder1'))
                    self.actTableWidget.cellWidget(k,1).setToolTip(actionTips.get(actionName).get('tips1'))
                    self.actTableWidget.cellWidget(k,2).setPlaceholderText(actionTips.get(actionName).get('holder2'))
                    self.actTableWidget.cellWidget(k,2).setToolTip(actionTips.get(actionName).get('tips2'))
                except:
                    pass

                #第四列 循环次数
                self.actTableWidget.setCellWidget(k,3,eval(actionArgs.get(actionName).get('arg3')))
                setQwidgetValue(self.actTableWidget.cellWidget(k,3),times)             
                #第五列
                self.actTableWidget.setCellWidget(k,4,waitTimeLineEdit())
                self.actTableWidget.cellWidget(k,4).setText(wt)

            #其他设置
            self.mainTimes.setValue(actionSet.get("mainTimes"))
            self.isInfinitely.setChecked(actionSet.get("isInfinitely"))
            self.isFailCollectCB.setChecked(actionSet.get("isFailCollect"))
            self.isFailStopCB.setChecked(actionSet.get("isFailStop"))
            self.mainTimes.setEnabled(actionSet.get("ismainTimes"))
            self.descriptionLineEdit.setText(actionSet.get("description"))
            self.tabWidget.setCurrentIndex(0)
            QMessageBox.information(None, "Comlete！", "参数导入完成！", QMessageBox.Ok)
            
        except FileNotFoundError:
            return False
        except Exception as e :
            print(e)
            QMessageBox.warning(None,"Error！", "参数导入失败！", QMessageBox.Ok)
            return False
        
    @error_handler
    def outputArea(self):
        fn = QtWidgets.QFileDialog.getSaveFileName(None, 'Save as', os.getcwd(),"Text Files(*.area)")[0]
        areaInfo = self.getAreaDict()
        feishulink = self.feiShuLink.text()
        try:
            with open(fn,"w+") as f:
                f.write(str(areaInfo)+'\n' +
                        str(feishulink)+'\n')
            
            QMessageBox.information(None, "Comlete！", "监控区域导出完成！", QMessageBox.Ok)
        except FileNotFoundError:
            return False
        except BaseException:
            QMessageBox.warning(None,"Error！", "监控区域导出失败！", QMessageBox.Ok)
        except Exception as e:
            print(e)

    #参数导入
    @error_handler
    def inputArea(self):
        fn = QtWidgets.QFileDialog.getOpenFileName(None, 'Open File', os.getcwd(),"Text Files(*.area)")[0]
        try:
            with open(fn,"r+") as f:
                ls = f.read().split('\n')
            areaInfo = eval(ls[0])
            feishulink = str(ls[1])
            #区域信息
            self.areaClr()
            for k,v in areaInfo.items():
                self.areaTableWidget.insertRow(k)
                areaTuple  = v.get('areaTuple')
                expectSec = v.get('expectSec')
                expectValue = v.get('expectValue')
                note = v.get('note')

                self.areaTableWidget.setCellWidget(k,0,areaLineEdit())
                self.areaTableWidget.setCellWidget(k,1,expectCombox())
                self.areaTableWidget.setCellWidget(k,2,expectLineEdit())
                self.areaTableWidget.setCellWidget(k,3,noteLineEdit())
                self.areaTableWidget.setCellWidget(k,4,pictureLabel())
                self.areaTableWidget.setCellWidget(k,5,ocrResultLineEdit())

                setQwidgetValue(self.areaTableWidget.cellWidget(k,0),areaTuple)
                setQwidgetValue(self.areaTableWidget.cellWidget(k,1),expectSec)
                setQwidgetValue(self.areaTableWidget.cellWidget(k,2),expectValue)
                setQwidgetValue(self.areaTableWidget.cellWidget(k,3),note)

            setQwidgetValue(self.feiShuLink,feishulink)
            self.tabWidget.setCurrentIndex(1)
            QMessageBox.information(None, "Comlete！", "监控区域导入完成！", QMessageBox.Ok)
            
        except FileNotFoundError:
            return False
        except Exception as e :
            print(e)
            QMessageBox.warning(None,"Error！", "监控区域导入失败！", QMessageBox.Ok)
            return False
        
      
    @error_handler
    def actionStart(self):
        #【前置操作】
        #创建相关文件夹
        # createFloder('data')
        # createFloder('areaData')
        # createReportXls()
        # self.dataFn = createFloder(datetime.now().strftime('data/{}_%Y%m%d%H%M%S'.format(self.dutInfo['ip'])))
        # self.logFn = path.join(self.dataFn,'log.log')
        
        actionResult = True
        self.doneTimes = 0
        self.passTimes = 0
        self.isReport = False
        # self.actionTimesDict = {}
        
        #检查report.xls是否处于打开状态，若是则打印告警信息：
        if is_file_open(reportFn):
            print(f"Warning:检测到{reportFn}处于打开状态，会导致拷机报告更新失败，请在拷机停止之前关闭该文件。")


        #等待拷机开始时间
        self.logOpenButton.setDisabled(True)
        waitForStart = int(self.waitForMain.text()) * 60
        if waitForStart:
            for t in range(waitForStart,0,-1):
                self.StatusLabel.setText(f"{t}s后开始拷机")
                sleep(1)
        #print(f'log将自动保存，路径:{self.logFn}')

        #【连接设备】
        self.StatusLabel.setText(f"连接设备中...")
        timePrint('开始连接设备...')
        self.mainTel = dutConnet(self.dutInfo)
        
        if not self.mainTel:
            timePrint("设备登录失败！")
            self.StatusLabel.setText(f"自动停止，请点击停止按钮结束拷机")
            return False
        
        self.StatusLabel.setText(f"收集设备初始信息...")
        
        if 'configCheck' in self.actionList:
            writeCfgTxt(self.mainTel.getCfgTxt(),path.join(self.dataFn,'cfg.txt'))

        if 'portStatusCheck' in self.actionList:
            self.portStatusDft = self.mainTel.getPortStatus()
        
        if 'slotStatusCheck' in self.actionList:
            self.slotStatusDft = self.mainTel.getAllSlotStatus()

        if 'fanStatusCheck' in self.actionList:
            self.fanStatusDft = self.mainTel.getFanStatus()

        if 'powerStatusCheck' in self.actionList:
            self.powerStatusDft = self.mainTel.getPowerStatus()

        if 'internalPortStatusCheck' in self.actionList:
            self.internalPortStatusDft = self.mainTel.getInternalPortStatus()

        if 'intfUsageCheck' in self.actionList:
            self.portUsageDft = self.mainTel.getAllPortUsage()

        #【开始拷机动作】
        #self.mainTel.do_cmd_noprint('ter no mo')  #关闭log打印

        mainTimes = 14159265358979 if self.isInfinitely.isChecked() else int(self.mainTimes.text())
        for actTimes in range(1,mainTimes + 1):
            # if not actionResult:
            #     break
            finalResult = True
            errorStep = {}
            for k,v in self.actionDict.items():
                # if not actionResult:
                #     break
                #【设备操作】
                #主备切换
                actionCn = v.get('action')
                action = actionNameDict.get(actionCn)
                times = int(v.get('times')) if v.get('times') else 0
                self.StatusLabel.setText(f"正在进行第{actTimes}轮拷机-第{k+1}步-{actionCn}")
                for _ in range(times):
                    if action == 'dutRedu':
                        self.mainTel.reduReady()
                        self.mainTel.do_Redu()
                        del self.mainTel
                        sleep(float(self.reduRcTime.text()))
                        self.mainTel = dutConnet(self.dutInfo) #重连
                        self.mainTel.waitForBackup()  #等待备机状态

                    #整机重启
                    if action == 'dutReload':
                        self.mainTel.do_Reload()
                        del self.mainTel
                        sleep(float(self.reloadRcTime.text()))
                        self.mainTel = dutConnet(self.dutInfo) 

                    #配置下发
                    if action == 'dutConfig':
                        self.mainTel.configFlapAction(path.join(self.dutCfgFr,v.get('arg_1').strip()),v.get('arg_2'))

                    #进程重启
                    if action == 'dutPkill':
                        self.mainTel.pkillAction(v.get('arg_1'),v.get('arg_2'))

                    #线卡上电
                    if action == 'slotPowerOn':
                        self.mainTel.powerOnAction([i.strip() for i in v.get('arg_1').split(',')],v.get('arg_2'))

                    if action == 'slotPowerOnNoWaitUp':
                        self.mainTel.powerOnAction([i.strip() for i in v.get('arg_1').split(',')],v.get('arg_2'),waitForUp=False)
                    
                    #线卡下电
                    if action == 'slotPowerOff':
                        self.mainTel.powerOffAction([i.strip() for i in v.get('arg_1').split(',')],v.get('arg_2'))
                    
                    #线卡Reset
                    if action == 'slotReset':
                        self.mainTel.resetSlotAction([i.strip() for i in v.get('arg_1').split(',')],v.get('arg_2'))
                    
                    if action == 'slotResetNoWaitUp':
                        self.mainTel.resetSlotAction([i.strip() for i in v.get('arg_1').split(',')],v.get('arg_2'),waitForUp=False)

                #【检查项】
                if action == 'coredumpCheck':
                    actionResult = self.mainTel.coredumpCheck()
                        
                if action == 'configCheck':
                    cfgNameNow = f'cfg_{getTimeStampNow()}.txt'
                    showRunTxt = self.mainTel.getCfgTxt()
                    writeCfgTxt(showRunTxt,path.join(self.dataFn,cfgNameNow))
                    actionResult = cfgCompare(path.join(self.dataFn,'cfg.txt'),path.join(self.dataFn,cfgNameNow))          

                if action == 'portUsageCheck':
                    portList = [port.strip() for port in v.get('arg_1').split('\n') if port.strip()]
                    actionResult = self.mainTel.ucmpCheck(portList,mode=v.get('arg_2'))

                if action == 'momCheck':
                    actionResult = self.mainTel.getMomInfoFlap(self.momWlFn)

                if action == 'areaCheck':
                    actionResult = self.runAreaCheck()
                
                if action == 'portStatusCheck':
                    actionResult = portStatusCheck(self.portStatusDft,self.mainTel.getPortStatus())

                if action == 'slotStatusCheck':
                    actionResult = slotStatusCheck(self.slotStatusDft,self.mainTel.getAllSlotStatus())

                if action == 'internalPortStatusCheck':
                    actionResult = portStatusCheck(self.internalPortStatusDft,self.mainTel.getInternalPortStatus())
                        
                if action == "showInfoCheck":
                    actionResult = self.mainTel.showInfoCheck(v.get('arg_1').strip(),v.get('arg_2'))

                if action == "showNoInfoCheck":
                    actionResult = self.mainTel.showInfoCheck(v.get('arg_1').strip(),v.get('arg_2'),isExist=False)

                if action == 'nsrCheck':
                    actionResult = self.mainTel.nsrCheck(v.get('arg_1').split(','))

                if action == 'fanStatusCheck':
                    actionResult = fanStatusCheck(self.fanStatusDft,self.mainTel.getFanStatus())
                
                if action == 'powerStatusCheck':
                    actionResult = powerStatusCheck(self.powerStatusDft,self.mainTel.getPowerStatus())

                if action == 'intfUsageCheck':
                    portList = [port.strip() for port in v.get('arg_1').split('\n') if port.strip()]
                    actionResult = portUsageCheck(self.portUsageDft,self.mainTel.portListUsage(portList),mode=v.get('arg_2'))

                if action == 'slotCpuCheck':
                    actionResult = thresCheck(self.mainTel.getSlotCPUInfo(),float(self.CPUErrorThreshold.text()),name='线卡CPU占用')
                
                if action == 'slotMemoryCheck':
                    actionResult = thresCheck(self.mainTel.getSlotMemoryInfo(),float(self.MemoryErrorThreshold.text()),name='线卡内存占用')

                if action == 'emmcCheck':
                    actionResult = thresCheck(self.mainTel.getEmmcInfo(),float(self.EMMCErrorThreshold.text()),name='线卡ECCM寿命',mode='lt')

                if action == 'selfHealingCheck':
                    actionResult = self.mainTel.selfHealingCheck()
                
                if action == 'clutserCheck':
                    actionResult = clusterStatusCheck(self.mainTel.getClusterInfo())
                
                if action == 'exceptionCheck':
                    actionResult = self.mainTel.exceptionCheck()

                if not actionResult:
                    finalResult = False
                    errorStep[str(k+1)] = actionCn
                
                isOverFlag = (not finalResult) and (self.isFailStopCB.isChecked())
                # print(isOverFlag)

                #检查项Fail，退出for循环
                if isOverFlag:
                    break
                else:
                    waitForNextAct = int(v.get('waitFor'))
                    if waitForNextAct:
                        for t in range(waitForNextAct,0,-1):
                            self.StatusLabel.setText(f"正在进行第{actTimes}轮拷机-第{k+1}步-{actionCn}-{t}s后执行下一操作")
                            sleep(1)
                    #sleep(float(v.get('waitFor')))
                    
            #退出外层for循环
            self.doneTimes += 1
            timePrint(f'第{actTimes}轮拷机结束，结果:【{resultDict[finalResult]}】')
            
            #统计：
            if finalResult:
                self.passTimes += 1

            if errorStep:
                print(f"检查项错误步骤:")
                printDict(errorStep,'-')
                fsLink = self.feiShuLink.text().strip()
                if fsLink:
                    try:
                        robot = FeishuTalk(fsLink)
                        robot.sendFailText(self.description,self.dutInfo.get('ip'),str(actTimes),errorStep)
                    except Exception as e:
                        print(e)
            
            if isOverFlag:
                # self.StatusLabel.setText(f"自动停止。。")
                timePrint('检查到Fail项，拷机自动停止！')
                break
        
        if actTimes == mainTimes:
            timePrint("拷机已达最大次数，自动停止。")
        
        # writeResultTxt(self.actionTimesDict,path.join(self.dataFn,'result.txt'))
        self.reportUpdate()

        #一键收集
        if (not finalResult) and (self.isFailCollectCB.isChecked()):
            self.StatusLabel.setText(f"一键收集中...")
            self.mainTel.dutCollect()

        self.StatusLabel.setText(f"自动停止，请点击停止按钮结束拷机")

    @error_handler
    def runMain(self):
        #【前置操作】
        #创建相关文件夹
        createFloder('data')
        createFloder('areaData')
        createFloder('dutCfg')
        createReportXls()

        self.dataFn = createFloder(datetime.now().strftime('data/{}_%Y%m%d%H%M%S'.format(self.dutIP.text())))
        self.logFn = path.join(self.dataFn,'log.log')
        createMoudleFile('dutCfg/配置下发说明.txt')
        # createMoudleFile('dutCfg/延时配置模板.txt')
        #获取设备信息并检查合法性
        self.dutCfgFr = self.dutCfgFrLE.text()
        self.momWlFn = self.momWlFnLE.text()
        errorCheckList = []

        try:
            self.dutInfo = self.getDutInfo()
            IPv4Address(self.dutInfo.get('ip'))
        except ValueError as e:
            errorCheckList.append('【设备信息】IP地址格式错误。')
        except Exception as e:
            print(e)
        
        #拷机描述
        self.description = self.descriptionLineEdit.text().strip()
        if not self.description:
            errorCheckList.append('【拷机设置】拷机描述不能为空。')
        #获取拷机参数并检查合法性
        self.actionDict = self.getActDict()
        if not self.actionDict:
            errorCheckList.append('【拷机设置】请添加拷机动作。')
        else:
            errorCheckList += actionDictCheck(self.actionDict,self.dutCfgFr)
        
        
        #获取监控区域参数并检查合法性，拷机设置中带有监控区域检查时才执行
        self.actionList = getActionsList(self.actionDict)
        if 'areaCheck' in self.actionList:
            self.areaDict = self.getAreaDict()
            if not self.areaDict:
                errorCheckList.append('【区域设置】请添加监控区域。')
            else:
                errorCheckList += areaDictCheck(self.getAreaDict())

        #mom白名单路径确定
        if 'momCheck' in self.actionList:
            if not fileRouteCheck(self.momWlFn):
                errorCheckList.append(f'【其他设置】0消息白名单文件{self.momWlFn}不存在，请重新选择文件。')
            
        
        if errorCheckList:
            print("请检查以下参数：")
            printList(errorCheckList,seq=True)
            rmdir(self.dataFn)
            self.logOpenButton.setDisabled(True)
            return 
        
        self.disableInput()
        self.clearAreaResults()
        #开始拷机线程
        self.mainThread = MainThread(target=self.actionStart)
        self.logWorker = Worker(self.logText,self.logFn,self.logMaxNum.text())
        self.logWorker.logSignal.connect(self.logTextClear)
        self.mainThread.start()
        self.logWorker.start()  
        # self.logThread.start()

    @error_handler
    def actionChanged(self):
        try:
            row = self.actTableWidget.currentRow() #获取当前行id
            action = self.actTableWidget.cellWidget(row,0).currentText() 
            self.actTableWidget.setCellWidget(row,1,eval(actionArgs.get(action).get('arg1')))
            self.actTableWidget.setCellWidget(row,2,eval(actionArgs.get(action).get('arg2')))
            self.actTableWidget.setCellWidget(row,3,eval(actionArgs.get(action).get('arg3')))
            self.actTableWidget.setCellWidget(row,4,waitTimeLineEdit())
            
            try:
                self.actTableWidget.cellWidget(row,1).setPlaceholderText(actionTips.get(action).get('holder1'))
                self.actTableWidget.cellWidget(row,1).setToolTip(actionTips.get(action).get('tips1'))
                self.actTableWidget.cellWidget(row,2).setPlaceholderText(actionTips.get(action).get('holder2'))
                self.actTableWidget.cellWidget(row,2).setToolTip(actionTips.get(action).get('tips2'))
            except:
                pass

        except:
            return -1

    @error_handler
    def runAreaCheck(self):
        errorList = [] #元素{'msg':xxx',imagPath':xx}\
        #self.statusLable.setText("正在获取监控数值。。")
        
        for k,v in self.areaDict.items():
            areaTuple = eval(v.get("areaTuple"))
            expectSec = expectDict[v.get("expectSec")]
            expectValue = int(v.get("expectValue"))
            note = v.get("note").strip()
            areaKnownAs = note if note else str(areaTuple)

            #判定预期值,最多判断3次
            for i in range(3):
                picFn = getAreaPic(areaTuple)
                ocrDigitResult = doOcr(picFn,self.psmCombox.currentText())
                if expectSec == 'ltbfe':
                    if ocrDigitResult != None:
                        try:
                            lastNum = int(getQwidgetValue(self.areaTableWidget.cellWidget(k,5)))
                        except:
                            lastNum = 0
                        minusResult =  ocrDigitResult - lastNum
                        judgeResult = (minusResult >= 0) and (minusResult <= expectValue)
                    else:
                        judgeResult = False
                else:
                    judgeResult = digitJudge(ocrDigitResult,expectValue,mode=expectSec)
                
                if judgeResult:
                    break
                else:
                    sleep(2)
                       
            #3次判断失败，取最后一次的值
            self.areaTableWidget.cellWidget(k,4).setPixmap(QPixmap(picFn))
            self.areaTableWidget.cellWidget(k,5).setText(str(ocrDigitResult))
            
            if not judgeResult:
                errorList.append({'msg':'区域【{}】的监控值为【{}】,与预期不符。(预期值:【{}】，与预期关系:【{}】)\n'.format(areaKnownAs,str(ocrDigitResult),str(expectValue),v.get("expectSec")),'imagPath':picFn})
                self.areaTableWidget.cellWidget(k,5).setStyleSheet("background-color:rgb(217,76,49)") #217;76;49
            else:
                self.areaTableWidget.cellWidget(k,5).setStyleSheet("background-color:rgb(146,208,80)") #146,208,80

        if errorList:
            fsLink = self.feiShuLink.text().strip()
            if fsLink:
                try:
                    robot = FeishuTalk(fsLink)
                    robot.sendTextMsgList(errorList)
                except Exception as e:
                    print(e)
        
        return len(errorList) == 0
    
    @error_handler
    def stopMain(self):
        try:
            self.mainTel.logout_host()
            del self.mainTel
        except Exception as e:
            pass

        try:
            self.logWorker.stop()
            del self.logWorker
        except Exception as e:
            pass
        
        try:
            self.mainThread.stop()
            del self.mainThread
            timePrint("拷机停止...")
        except AttributeError as e:
            print(e)
        finally:
            self.enableInput()
            self.StatusLabel.setText(f"未运行")
            self.reportUpdate()

        try:
            self.writeRestLog()
            self.logOpenButton.setEnabled(True)
        except:
            pass

        
    @error_ignore
    def getAreaTp(self):
        """线程安全的坐标获取方法"""
        try:
            self.disableInput()
            self.stopButton.setEnabled(False)
            self.logText.clear()
            
            # 停止现有线程
            if hasattr(self, 'current_thread') and self.current_thread.isRunning():
                self.current_thread.quit()
                self.current_thread.wait()
            
            # 创建线程
            t = getAreaThread()
            
            # 连接完成信号
            t.finished_signal.connect(self._on_area_thread_finished)
            
            # 连接结果信号
            t.result_signal.connect(self._on_area_thread_result)
            
            # 连接错误信号
            t.error_signal.connect(self._on_area_thread_error)
            
            # 将线程对象保存为实例变量，避免被垃圾回收
            self.current_thread = t
            t.start()
            
        except Exception as e:
            print(f"启动坐标获取线程失败: {e}")
            self.enableInput()
            self.stopButton.setEnabled(True)
        
        
    # 坐标获取线程的回调方法
    def _on_area_thread_finished(self):
        """坐标获取线程完成的回调"""
        try:
            self.enableInput()
            self.stopButton.setEnabled(True)
        except Exception as e:
            print(f"坐标获取完成处理失败: {e}")

    def _on_area_thread_result(self, result):
        """坐标获取线程结果的回调"""
        try:
            # 存储结果到实例变量
            self.thread_result = result
            
            # 自动将结果填充到lineedit上
            if result is not None:
                self.ocrTupleLineEdit.setText(str(result))
            else:
                print('选择已取消')
                
        except Exception as e:
            print(f"坐标获取结果处理失败: {e}")

    def _on_area_thread_error(self, error_msg):
        """坐标获取线程错误的回调"""
        try:
            print(f"坐标获取错误: {error_msg}")
            self.ocrTupleLineEdit.setText(f'坐标获取失败: {error_msg}')
        except Exception as e:
            print(f"坐标获取错误处理失败: {e}")

    def reportUpdate(self):
        # getActionDictXls(reportFn)
        if self.isReport:
            return
        if not self.doneTimes:
            return
        upgradeInfo = {self.description:(self.doneTimes,self.passTimes)}
        # doneDict = self.actionTimesDict
        xlsDict = getActionDictXls(reportFn)
        # finalDict = {}
        # finalDict.update(xlsDict)
        if xlsDict.get(self.description):
            xlsDict[self.description] = tuple([sum(x) for x in zip(xlsDict[self.description], upgradeInfo[self.description])])
        else:
            xlsDict[self.description] = upgradeInfo[self.description]

        print("本次拷机执行轮次:{}, PASS次数:{}, PASS率:{:.2%}".format(self.doneTimes,self.passTimes,self.passTimes/self.doneTimes))
        try:
            writeXlsDict(xlsDict,reportFn)
            print(f"结果已更新至{os.path.abspath(reportFn)}")
        except:
            print(f"拷机报告更新失败！拷机停止之前请关闭{os.path.abspath(reportFn)}！")
        self.isReport = True

    def openUrlOcrTip(self):
        # 在槽函数中调用 QDesktopServices.openUrl() 方法并传入要打开的链接
        url = QUrl(r"http://conf.ruijie.work/pages/viewpage.action?pageId=473139863")
        QDesktopServices.openUrl(url)

    def openUrlwhiteListTip(self):
        QMessageBox.warning(None,"´ᴥ`", '还没写~' , QMessageBox.Ok)
    
    def openInfoQbox(self):
        QMessageBox.information(None,"软件信息", aboutInfo , QMessageBox.Ok)

    def logTextClear(self):
        self.logText.clear()
    
    def writeRestLog(self):
        # sleep(1)
        restLog = self.logText.toPlainText()
        writeCfgTxt(restLog,self.logFn,mode="a+")

    def getCurOption(self):
        actSet = {"mainTimes":int(self.mainTimes.text()),
                "isInfinitely":self.isInfinitely.isChecked(),
                "isFailCollect":self.isFailCollectCB.isChecked(),
                'isFailStop':self.isFailStopCB.isChecked(),
                'ismainTimes':self.mainTimes.isEnabled(),
                'description':self.descriptionLineEdit.text().strip()}
        
        if actSet.get("isInfinitely"):
            actSet['ismainTimes'] = False
        else:
            actSet['ismainTimes'] = True
        
        return actSet
    
    # OCR测试专用信号类
    class OCRTestSignals(QObject):
        update_result = pyqtSignal(str)  # 更新识别结果
        update_image = pyqtSignal(str)   # 更新图片
        update_status = pyqtSignal(bool) # 更新按钮状态
        show_error = pyqtSignal(str)     # 显示错误信息

    @error_handler
    def runOcrTest(self):
        """线程安全的OCR测试方法"""
        try:
            # 参数验证
            area_tuple_text = self.ocrTupleLineEdit.text().strip()
            if not area_tuple_text:
                self.ocrTestResultLineEdit.setText('错误：坐标值不能为空')
                return
                
            # 安全解析坐标
            try:
                area_tuple = eval(area_tuple_text)
                if not isinstance(area_tuple, tuple) or len(area_tuple) != 4:
                    raise ValueError("坐标必须是4个元素的元组")
                
                # 验证坐标范围
                x1, y1, x2, y2 = area_tuple
                if not all(isinstance(coord, (int, float)) for coord in area_tuple):
                    raise ValueError("所有坐标必须是数字")
                if x1 >= x2 or y1 >= y2:
                    raise ValueError("坐标范围无效：左上角坐标必须小于右下角坐标")
                    
            except Exception as e:
                self.ocrTestResultLineEdit.setText(f'错误：坐标格式不正确 - {str(e)}')
                return
            
            psm_value = self.psmCombox.currentText()
            
            # 创建信号实例
            if not hasattr(self, 'ocr_test_signals'):
                self.ocr_test_signals = self.OCRTestSignals()
            
            # 连接信号到槽函数
            self.ocr_test_signals.update_result.connect(self._update_ocr_result)
            self.ocr_test_signals.update_image.connect(self._update_ocr_image)
            self.ocr_test_signals.update_status.connect(self._update_button_status)
            self.ocr_test_signals.show_error.connect(self._show_ocr_error)
            
            # 停止现有线程
            if hasattr(self, 'ocr_test_thread') and self.ocr_test_thread.isRunning():
                self.ocr_test_thread.quit()
                self.ocr_test_thread.wait()
            
            # 创建并启动线程
            self.ocr_test_thread = self.SafeOCRTestThread(area_tuple, psm_value, self.ocr_test_signals)
            self.ocr_test_thread.start()
            
        except Exception as e:
            self.ocrTestResultLineEdit.setText(f'启动识别失败：{str(e)}')
    # 线程安全的OCR测试线程
    class SafeOCRTestThread(QThread):
        def __init__(self, area_tuple, psm_value, signals, parent=None):
            super().__init__(parent)
            self.area_tuple = area_tuple
            self.psm_value = psm_value
            self.signals = signals
            self.is_running = True
            
        def run(self):
            """在线程中执行OCR识别"""
            try:
                # 禁用按钮
                self.signals.update_status.emit(False)
                
                # 执行OCR识别
                pic_fn = getAreaPic(self.area_tuple)
                ocr_result = doOcr(pic_fn, self.psm_value)
                
                # 通过信号发送结果
                self.signals.update_image.emit(pic_fn)
                self.signals.update_result.emit(str(ocr_result))
                
            except Exception as e:
                # 发送错误信号
                error_msg = f'识别错误！{str(e)}'
                self.signals.show_error.emit(error_msg)
                
            finally:
                # 恢复按钮状态
                self.signals.update_status.emit(True)
        
        def stop(self):
            """停止线程"""
            self.is_running = False
            self.terminate()
            self.wait()

    # 线程安全的UI更新方法
    def _update_ocr_result(self, result):
        """更新OCR结果（线程安全）"""
        self.ocrTestResultLineEdit.setText(result)
    
    def _update_ocr_image(self, image_path):
        """更新OCR图片（线程安全）"""
        try:
            pixmap = QPixmap(image_path)
            self.ocrTestPictureLabel.setPixmap(pixmap)
        except Exception as e:
            print(f"更新图片失败: {e}")
    
    def _update_button_status(self, enabled):
        """更新按钮状态（线程安全）"""
        self.ocrTestBtn.setEnabled(enabled)
    
    def _show_ocr_error(self, error_msg):
        """显示OCR错误（线程安全）"""
        self.ocrTestResultLineEdit.setText(error_msg)

    # @error_handler
    # def runOcrTestThread(self):
    #     self.ocrTestThread = MainThread(target=self.runOcrTest)
    #     self.ocrTestThread.start()
    #     # self.ocrTestThread.exec()
